import { Product } from "@/types/product"

export const products: Product[] = [
  {
    id: 1,
    title: "ScreenWatch Series 9",
    price: 399,
    category: "wearables",
    image: "/products/1.png",
    description: "The ultimate smartwatch with advanced health tracking and a brighter always-on display.",
    rating: { rate: 4.8, count: 1200 },
  },
  {
    id: 2,
    title: "Ergo SmartMouse",
    price: 89,
    category: "mouse",
    image: "/products/2.png",
    description: "Ergonomic wireless mouse designed for comfort during long gaming or work sessions.",
    rating: { rate: 4.5, count: 850 },
  },
  {
    id: 3,
    title: "Smart Laser Pointer",
    price: 35,
    category: "accessories",
    image: "/products/3.png",
    description: "Professional presentation clicker with a bright green laser and 100ft range.",
    rating: { rate: 4.6, count: 420 },
  },
  {
    id: 4,
    title: "Holo Laptop Pro 15",
    price: 1499,
    category: "laptop",
    image: "/products/4.png",
    description: "High-performance laptop with holographic display capabilities and a powerful GPU.",
    rating: { rate: 4.9, count: 215 },
  },
  {
    id: 5,
    title: "Sonic Mechanical Keyboard",
    price: 145,
    category: "keyboard",
    image: "/products/1.png", /* reusing images for dummy data */
    description: "Tactile mechanical keyboard with customizable RGB lighting and hot-swappable switches.",
    rating: { rate: 4.7, count: 320 },
  },
  {
    id: 6,
    title: "UltraWide Monitor 34\"",
    price: 450,
    category: "monitor",
    image: "/products/2.png",
    description: "A gorgeous 34-inch ultrawide monitor perfect for multitasking and immersive gaming.",
    rating: { rate: 4.8, count: 500 },
  },
  {
    id: 7,
    title: "NoiseCancelling Headphones X",
    price: 299,
    category: "audio",
    image: "/products/3.png",
    description: "Industry-leading wireless noise-cancelling headphones with 30-hour battery life.",
    rating: { rate: 4.9, count: 2100 },
  },
  {
    id: 8,
    title: "Fitness Tracker Fit Plus",
    price: 99,
    category: "wearables",
    image: "/products/4.png",
    description: "Lightweight fitness tracker with continuous heart rate monitoring and sleep tracking.",
    rating: { rate: 4.4, count: 760 },
  },
  {
    id: 9,
    title: "Ultralight Gaming Mouse",
    price: 75,
    category: "mouse",
    image: "/products/1.png",
    description: "A super lightweight gaming mouse weighing only 60 grams for incredible precision.",
    rating: { rate: 4.6, count: 910 },
  },
  {
    id: 10,
    title: "Creator Laptop 14\"",
    price: 1299,
    category: "laptop",
    image: "/products/2.png",
    description: "Thin and light laptop designed for digital creators with a color-accurate OLED screen.",
    rating: { rate: 4.7, count: 180 },
  },
  {
    id: 11,
    title: "Silent Typing Keyboard",
    price: 110,
    category: "keyboard",
    image: "/products/3.png",
    description: "A quiet, low-profile keyboard ideal for office environments and late-night productivity.",
    rating: { rate: 4.5, count: 340 },
  },
  {
    id: 12,
    title: "Studio Monitor Speakers",
    price: 250,
    category: "audio",
    image: "/products/4.png",
    description: "High-fidelity studio monitors delivering crisp highs and balanced bass for audio mixing.",
    rating: { rate: 4.8, count: 420 },
  },
  {
    id: 13,
    title: "Portable SSD 2TB",
    price: 180,
    category: "accessories",
    image: "/products/1.png",
    description: "A rugged, blazing-fast portable solid-state drive with 2TB of storage capacity.",
    rating: { rate: 4.9, count: 1500 },
  },
  {
    id: 14,
    title: "Curved Gaming Monitor 27\"",
    price: 320,
    category: "monitor",
    image: "/products/2.png",
    description: "27-inch 1440p curved monitor with a 165Hz refresh rate for buttery-smooth gameplay.",
    rating: { rate: 4.7, count: 680 },
  },
  {
    id: 15,
    title: "True Wireless Earbuds",
    price: 149,
    category: "audio",
    image: "/products/3.png",
    description: "Compact wireless earbuds featuring active noise cancellation and a wireless charging case.",
    rating: { rate: 4.6, count: 1250 },
  }
]